name = "NicheMapper"
uuid = "0dd11925-8a82-4e26-8e90-74fb12eeca45"
authors = ["Michael Kearney <m.kearney@unimelb.edu.au>", "Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10"
